version: 2.1 # Use version 2.1 to enable orb usage.
defaults: &dockerbase
  docker:
    - image: circleci/node:13.8.0
  working_directory: /tmp

commands: 
  sayhello:
    description: "Simple command to say hello"
    parameters: 
      hello_to: 
        type: string
        default: "Hello World"
      file_name:
        type: string
        default: "ss_workspace/test.txt"
    steps:
      - run: echo << parameters.hello_to >> >> << parameters.file_name >>

jobs:
  print_hello_user:
    <<: *dockerbase
    steps:
      - run: mkdir -p ss_workspace 
      - run: mkdir -p cachefolder 
      - sayhello: 
          hello_to: "Hello my dear $CIRCLE_PROJECT_USERNAME !"
          file_name: "/tmp/ss_workspace/ssfile1.txt"
      - sayhello: 
          hello_to: "Hello my dear $CIRCLE_PROJECT_USERNAME !"
          file_name: "/tmp/cachefolder/test.txt"
      - save_cache:
          key: v1-my-project-{{ checksum "cachefolder/test.txt" }}
          paths:
            - /tmp/cachefolder/test.txt
      - persist_to_workspace:
          root: ss_workspace
          paths:
            - ssfile1.txt

  get_hello_user:
    <<: *dockerbase
    steps:
      - attach_workspace:
          at: /tmp/ss_workspace
      - restore_cache:
          key: v1-my-project
      - run: pwd
      - run: echo Good Morning >>/tmp/ss_workspace/ssfile1.txt
      - run: cat /tmp/ss_workspace/ssfile1.txt
      - run: pwd
      - run: cd /tmp && pwd && cd cachefolder && cp test.txt test1.txt
      - run: ls -la
      - run: echo "testing cache" >> /tmp/cachefolder/test.txt
      - run: cat /tmp/cachefolder/test.txt
      - run: cat /tmp/cachefolder/test1.txt
      

workflows:
  say-hello-workflow:
    jobs:
      - print_hello_user
      - get_hello_user:
          requires:
            - print_hello_user